### ISSUE TITLE
破折号不能正确显示

### ISSUE THREAD

**Issue by xiaomingtt** [TikaFlow/UTF8ToGB2312#1]
“——”转换结果为空。

**Comment by TikaFlow** [comment]
GB2312中并没有收录破折号，因此无法转换。
可以在[千千秀字](https://www.qqxiuzi.cn/bianma/zifuji.php)查询："——"或一半："—"，可知，GB2312字符集中没有收录。
UTF8转GB2312要求该字符在GB2312中有收录才可正确转换。

介绍参见[我的博客](https://blog.tika-flow.top/post/%E8%A7%A3%E5%86%B3%E4%B8%B2%E5%8F%A3%E5%B1%8F%E4%B8%AD%E6%96%87%E7%BC%96%E7%A0%81%E9%97%AE%E9%A2%98)
